spring:
  application:
    name: Twitter-hash-tags
  datasource:
    url: jdbc:mysql://localhost:3306/twitterdata
    username: root
    password: harish254
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    generte-ddl : false
    hibernate:
      ddl-auto: none
    show_sql: true
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 10010